# Generated by Django 4.1.1 on 2022-09-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('order', models.BigIntegerField(blank=True, default=0, null=True)),
                ('subcategory', models.ManyToManyField(blank=True, null=True, to='main_app.category', verbose_name='subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
                ('category', models.ManyToManyField(to='main_app.category', verbose_name='category')),
            ],
        ),
    ]
