# Generated by Django 4.1.1 on 2022-09-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_category_subcategory_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default='Null', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.category'),
        ),
    ]
